import '../entities/challenge_definition.dart';

abstract final class BuiltInChallengeCatalog {
  static const all = [
    ChallengeDefinition(
      id: 'weekly_5k',
      title: 'Run 5 km this week',
      description: 'Build your weekly Motion Path with 5 total kilometers.',
      category: ChallengeCategory.distance,
      period: ChallengePeriod.weekly,
      targetValue: 5,
      unit: ChallengeUnit.kilometers,
      xpReward: 80,
      isRepeatable: true,
    ),
    ChallengeDefinition(
      id: 'weekly_3_runs',
      title: 'Complete 3 runs this week',
      description: 'Stack three running days into your week.',
      category: ChallengeCategory.runCount,
      period: ChallengePeriod.weekly,
      targetValue: 3,
      unit: ChallengeUnit.runs,
      xpReward: 100,
      isRepeatable: true,
    ),
    ChallengeDefinition(
      id: 'weekly_60_minutes',
      title: 'Run for 60 total minutes this week',
      description: 'Accumulate one hour of movement this week.',
      category: ChallengeCategory.duration,
      period: ChallengePeriod.weekly,
      targetValue: 60,
      unit: ChallengeUnit.minutes,
      xpReward: 90,
      isRepeatable: true,
    ),
    ChallengeDefinition(
      id: 'monthly_20k',
      title: 'Run 20 km this month',
      description: 'Trace a 20 km monthly Motion Path.',
      category: ChallengeCategory.distance,
      period: ChallengePeriod.monthly,
      targetValue: 20,
      unit: ChallengeUnit.kilometers,
      xpReward: 180,
      isRepeatable: true,
    ),
    ChallengeDefinition(
      id: 'monthly_8_runs',
      title: 'Complete 8 runs this month',
      description: 'Create a consistent running month.',
      category: ChallengeCategory.runCount,
      period: ChallengePeriod.monthly,
      targetValue: 8,
      unit: ChallengeUnit.runs,
      xpReward: 200,
      isRepeatable: true,
    ),
    ChallengeDefinition(
      id: 'monthly_4_training',
      title: 'Complete 4 training sessions this month',
      description: 'Follow structured training four times this month.',
      category: ChallengeCategory.trainingSessions,
      period: ChallengePeriod.monthly,
      targetValue: 4,
      unit: ChallengeUnit.sessions,
      xpReward: 160,
      isRepeatable: true,
    ),
    ChallengeDefinition(
      id: 'lifetime_50k',
      title: 'Reach 50 total kilometers',
      description: 'Cross your first 50 lifetime kilometers.',
      category: ChallengeCategory.distance,
      period: ChallengePeriod.lifetime,
      targetValue: 50,
      unit: ChallengeUnit.kilometers,
      xpReward: 250,
      isRepeatable: false,
    ),
    ChallengeDefinition(
      id: 'lifetime_20_runs',
      title: 'Complete 20 total runs',
      description: 'Make twenty completed runs part of your story.',
      category: ChallengeCategory.runCount,
      period: ChallengePeriod.lifetime,
      targetValue: 20,
      unit: ChallengeUnit.runs,
      xpReward: 260,
      isRepeatable: false,
    ),
  ];
}
